---
- name: Nginx súper simple
  hosts: webservers
  become: yes
  
  tasks:
    - name: Instalar Nginx
      package:
        name: nginx
        state: present
    
    - name: Iniciar Nginx
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Mostrar IP
      debug:
        msg: "✅ Nginx funcionando en: http://{{ ansible_default_ipv4.address }}"
