---
- name: Test de conectividad
  hosts: webservers
  
  tasks:
    - name: Ping test
      ping:
    
    - name: Mostrar info básica
      debug:
        msg: |
          🔗 Conectado a: {{ inventory_hostname }}
          💻 OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          🏠 IP: {{ ansible_default_ipv4.address }}
          👤 Usuario: {{ ansible_user_id }}
