---
- hosts: localhost
  connection: local
  tasks:
    - name: Crear directorio
      file:
        path: /tmp/mi-test
        state: directory
    
    - name: Crear archivo
      copy:
        content: "¡Hola desde Ansible!"
        dest: /tmp/mi-test/saludo.txt
    
    - name: Mostrar contenido
      debug:
        msg: "Archivo creado en /tmp/mi-test/saludo.txt"
