---
- name: Instalar y configurar Nginx básico
  hosts: webservers
  become: yes
  
  tasks:
    - name: Actualizar cache de paquetes (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    
    - name: Instalar Nginx
      package:
        name: nginx
        state: present
    
    - name: Crear página personalizada
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Nginx desde Ansible</title>
              <style>
                  body { 
                      font-family: Arial, sans-serif; 
                      margin: 40px; 
                      background: #f0f8ff;
                  }
                  .container { 
                      max-width: 600px; 
                      margin: 0 auto; 
                      padding: 20px; 
                      background: white; 
                      border-radius: 10px; 
                      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                  }
                  h1 { color: #2c3e50; }
                  .info { 
                      background: #ecf0f1; 
                      padding: 15px; 
                      border-radius: 5px; 
                      margin: 20px 0;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🚀 ¡Nginx instalado con Ansible!</h1>
                  <p>Este servidor web fue configurado automáticamente.</p>
                  
                  <div class="info">
                      <h3>Información del servidor:</h3>
                      <ul>
                          <li><strong>Hostname:</strong> {{ inventory_hostname }}</li>
                          <li><strong>IP:</strong> {{ ansible_default_ipv4.address }}</li>
                          <li><strong>OS:</strong> {{ ansible_distribution }} {{ ansible_distribution_version }}</li>
                          <li><strong>Arquitectura:</strong> {{ ansible_architecture }}</li>
                          <li><strong>Fecha de instalación:</strong> {{ ansible_date_time.date }}</li>
                      </ul>
                  </div>
                  
                  <p>✅ Ansible funcionando correctamente con versión global!</p>
              </div>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      when: ansible_os_family == "Debian"
    
    - name: Crear página personalizada (RedHat)
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head><title>Nginx desde Ansible</title></head>
          <body>
              <h1>🚀 ¡Nginx instalado con Ansible!</h1>
              <p>Servidor: {{ inventory_hostname }}</p>
              <p>OS: {{ ansible_distribution }} {{ ansible_distribution_version }}</p>
              <p>✅ Funcionando en RedHat/CentOS</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'
      when: ansible_os_family == "RedHat"
    
    - name: Iniciar y habilitar Nginx
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Verificar que Nginx responde
      uri:
        url: "http://{{ ansible_default_ipv4.address }}"
        method: GET
        status_code: 200
      register: nginx_check
    
    - name: Mostrar resultado
      debug:
        msg: |
          ✅ ¡Nginx instalado y funcionando!
          🌐 Accede a: http://{{ ansible_default_ipv4.address }}
          📊 Status code: {{ nginx_check.status }}
